name: Continuous Integration

on:
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Node.js installation
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Dependencies Installation
      run: npm install
